name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  # CMAKE_GENERATOR: Ninja
  # VCPKG_ROOT: "$VCPKG_INSTALLATION_ROOT"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      #  Ninja is not exist on ci.
      # - name: Print Ninja version
      #   run: |
      #       ninja --version

      - name: Directly invoke `vcpkg install`
        run: |
            vcpkg install

      - name: Build project
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release && cmake --build build -j

      - name: Package project
        run: |
            cd build && cpack

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}.tar.gz
          path: build/*.tar.gz
